// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrYYlSDtC6iQ9sATl_x_GkOexbRlT8P6s',
    appId: '1:432875763778:web:1beaf7e9067e2dfe4595db',
    messagingSenderId: '432875763778',
    projectId: 'quickmove-demo',
    authDomain: 'quickmove-demo.firebaseapp.com',
    storageBucket: 'quickmove-demo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7LtJLLEnuBArW9VVrE-Q_tdmQQ8qqQBA',
    appId: '1:432875763778:android:d59139d23de67e674595db',
    messagingSenderId: '432875763778',
    projectId: 'quickmove-demo',
    storageBucket: 'quickmove-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7Z93ReXMbZ2yfz8I-Yp2FRQQmpjzFxi0',
    appId: '1:432875763778:ios:20b522fc1125632a4595db',
    messagingSenderId: '432875763778',
    projectId: 'quickmove-demo',
    storageBucket: 'quickmove-demo.firebasestorage.app',
    iosBundleId: 'com.example.miniLogisticsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7Z93ReXMbZ2yfz8I-Yp2FRQQmpjzFxi0',
    appId: '1:432875763778:ios:20b522fc1125632a4595db',
    messagingSenderId: '432875763778',
    projectId: 'quickmove-demo',
    storageBucket: 'quickmove-demo.firebasestorage.app',
    iosBundleId: 'com.example.miniLogisticsApp',
  );
}
